version: '3'

services:
  database:
    image: mariadb
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
  openenventory:
    build:
      context: .
      dockerfile: docker/openenventory
    container_name: oe_web
    environment:
      DB_SERVER: db1
      SINGLE_DB: 1
    ports:
      - 8888:80
    depends_on:
      - database
